const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function open(page,{fallback=false}={}){
 await page.route(/^https?:\/(?!\/127\.0\.0\.1)/,r=>r.abort());
 await page.addInitScript(({fallback})=>{localStorage.setItem('compasso.ux.mode.v1','essential');if(fallback)Object.defineProperty(window,'indexedDB',{value:undefined,configurable:true});globalThis.CompassoDriveSync||={prepareLocalState(input){return{data:structuredClone(input),baseline:new Map()}},activateLocalState(){}}},{fallback});
 await page.goto('/?view=capabilities',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>CompassoFeatures?.installed&&CompassoPwaLifecycle?.snapshot().coherent);
 await page.evaluate(async()=>{state.data.learningOutcomes=[];state.data.learningSignals=[];state.data.executionSessions=[];state.data.evidence=[];state.data.behavioralExperiments=[];await CompassoStorage.save('compasso.app.v1',state.data);renderAll()});
 await page.locator('[data-outcome-new]').first().click();await expect(page.locator('#outcomeImportancePanel')).toBeHidden();await page.locator('#learningOutcomeCapability').fill('Explicar uma ideia');await page.locator('#learningOutcomeAttempt').fill('Explicar um exemplo');await page.locator('#learningOutcomeForm [type="submit"]').click();await expect(page.locator('#learningOutcomeDialog')).toBeHidden();await page.locator('[data-outcome-edit]').click();
}
async function data(page){return page.evaluate(()=>structuredClone({outcomes:state.data.learningOutcomes,signals:state.data.learningSignals,sessions:state.data.executionSessions,evidence:state.data.evidence,experiments:state.data.behavioralExperiments}))}
async function choose(page,value){await page.locator('#outcomeImportancePanel').evaluate(d=>d.open=true);await page.locator('#outcomeImportanceChoice').selectOption(value)}
const action=p=>p.locator('#outcomeImportanceAction');
async function saved(page){await page.locator('#learningOutcomeForm [type="submit"]').click();await expect(page.locator('#learningOutcomeDialog')).toBeHidden()}
async function contrast(locator,property='color'){
 return locator.evaluate((node,property)=>{const lum=c=>{const [r,g,b]=c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>{const x=n/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*r+.7152*g+.0722*b};let background='rgb(255,255,255)';for(let e=node;e;e=e.parentElement){const c=getComputedStyle(e).backgroundColor;if(!c.startsWith('rgba')||!c.endsWith(', 0)')){background=c;break}}const x=lum(getComputedStyle(node)[property]),y=lum(background);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)},property);
}

test('optional answers never save; continue preserves record and reset',async({page})=>{
 await open(page);const before=await data(page);await expect(page.locator('#outcomeImportancePanel')).not.toHaveAttribute('open','');await expect(action(page)).toBeHidden();
 for(const [value,label] of [['yes','Continuar com a capacidade'],['partial','Ajustar próxima tentativa'],['no','Arquivar capacidade']]){await choose(page,value);await expect(action(page)).toHaveText(label);await expect(action(page)).toHaveAccessibleName(label);expect(await data(page)).toEqual(before)}
 await choose(page,'');await expect(action(page)).toBeHidden();for(const value of ['invalid','constructor','__proto__']){await page.evaluate(value=>document.querySelector('#outcomeImportanceChoice').append(new Option('Inválido',value)),value);await choose(page,value);await expect(action(page)).toBeHidden();expect(await data(page)).toEqual(before)}
 await choose(page,'yes');await action(page).click();await expect(page.locator('#learningOutcomeDialog')).toBeHidden();await expect(page.locator('[data-outcome-edit]')).toBeFocused();expect(await data(page)).toEqual(before);await page.locator('[data-outcome-edit]').click();await expect(page.locator('#outcomeImportanceChoice')).toHaveValue('');await expect(page.locator('#outcomeImportancePanel')).not.toHaveAttribute('open','');await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>CompassoPwaLifecycle?.snapshot().coherent);expect(await data(page)).toEqual(before);
});
test('adjust only focuses; continue respects draft discard; ordinary save',async({page})=>{
 await open(page);const before=await data(page);await choose(page,'partial');await action(page).click();await expect(page.locator('#learningOutcomeAttempt')).toBeFocused();await expect(page.locator('#learningOutcomeAttempt')).toHaveValue('Explicar um exemplo');expect(await data(page)).toEqual(before);await page.locator('#learningOutcomeAttempt').fill('Explicar dois exemplos');await choose(page,'yes');page.once('dialog',d=>d.dismiss());await action(page).click();await expect(page.locator('#learningOutcomeDialog')).toBeVisible();await expect(page.locator('#learningOutcomeAttempt')).toHaveValue('Explicar dois exemplos');expect(await data(page)).toEqual(before);await saved(page);const after=await data(page);expect(after.outcomes[0].nextAttempt.text).toBe('Explicar dois exemplos');expect(after.outcomes[0].schemaVersion).toBe(1);expect(Object.keys(after.outcomes[0]).some(k=>/importance|value/i.test(k))).toBe(false);expect(after.signals).toEqual(before.signals);expect(after.sessions).toEqual(before.sessions);
});
test('archive explicit confirmation discards draft and keeps historical text; reactivate',async({page})=>{
 await open(page);const before=await data(page);await page.locator('#learningOutcomeAttempt').fill('Rascunho descartado');await choose(page,'no');page.once('dialog',d=>d.dismiss());await action(page).click();expect(await data(page)).toEqual(before);await expect(page.locator('#learningOutcomeAttempt')).toHaveValue('Rascunho descartado');page.once('dialog',async d=>{expect(d.message()).toContain('não salvas serão descartadas');await d.accept()});await action(page).click();await expect(page.locator('#learningOutcomeDialog')).toBeHidden();const after=await data(page);expect(after.outcomes[0].status).toBe('archived');expect(after.outcomes[0].nextAttempt).toEqual(before.outcomes[0].nextAttempt);expect(after.signals).toEqual(before.signals);await page.locator('[data-outcome-mode="archived"]').click();await page.locator('[data-outcome-edit]').click();await expect(page.locator('#outcomeImportancePanel')).toBeHidden();await page.keyboard.press('Escape');await page.locator('[data-outcome-status]').click();expect((await data(page)).outcomes[0].status).toBe('active');expect((await data(page)).outcomes[0].nextAttempt).toEqual(before.outcomes[0].nextAttempt);
});
test('archive failure preserves draft; busy and retry save exactly once',async({page})=>{
 await open(page);await choose(page,'no');const before=await data(page);await page.evaluate(()=>{window.__storage=CompassoStorage;window.CompassoStorage={...CompassoStorage,save:async()=>false}});page.on('dialog',d=>d.accept());await action(page).click();await expect(page.locator('#learningOutcomeError')).toContainText('Não foi possível salvar');expect(await data(page)).toEqual(before);await expect(page.locator('#outcomeImportanceChoice')).toHaveValue('no');await expect(action(page)).toBeEnabled();await page.evaluate(()=>{window.__calls=0;window.CompassoStorage={...window.__storage,save:async(...args)=>{window.__calls++;await new Promise(r=>window.__release=r);return window.__storage.save(...args)}}});await action(page).click();await expect(action(page)).toBeDisabled();await page.keyboard.press('Escape');await expect(page.locator('#learningOutcomeDialog')).toBeVisible();await action(page).dispatchEvent('click');expect(await page.evaluate(()=>window.__calls)).toBe(1);await page.evaluate(()=>window.__release());await expect(page.locator('#learningOutcomeDialog')).toBeHidden();expect((await data(page)).outcomes[0].status).toBe('archived');
});
test('stale target cannot archive or reactivate',async({page})=>{
 await open(page);await choose(page,'no');await page.evaluate(()=>{state.data.learningOutcomes[0].status='archived'});const before=await data(page);await action(page).click();await expect(page.locator('#learningOutcomeError')).toContainText('não está mais ativa');expect(await data(page)).toEqual(before);await page.evaluate(()=>{state.data.learningOutcomes=[]});await action(page).click();expect((await data(page)).outcomes).toEqual([]);
});
for(const fallback of [false,true])test(`ordinary adjustment backup/offline ${fallback?'fallback':'IDB'}`,async({page,context})=>{
 await open(page,{fallback});await choose(page,'partial');await action(page).click();await page.locator('#learningOutcomeAttempt').fill('Meu próximo exemplo');await saved(page);const before=await data(page);await page.locator('#settingsBtn').click();page.once('dialog',d=>d.accept());const downloading=page.waitForEvent('download');await page.locator('#exportBtn').click();const download=await downloading;await page.locator('#importInput').setInputFiles(await download.path());await page.locator('#restoreConfirmBtn').click();await expect(page.locator('#restoreDialog')).toBeHidden();expect(await data(page)).toEqual(before);await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>CompassoPwaLifecycle?.snapshot().coherent);expect(await data(page)).toEqual(before);await page.locator('[data-outcome-edit]').click();await expect(page.locator('#outcomeImportanceChoice')).toHaveValue('');await choose(page,'no');page.once('dialog',d=>d.accept());await action(page).click();await expect(page.locator('#learningOutcomeDialog')).toBeHidden();await page.reload();await page.waitForFunction(()=>CompassoPwaLifecycle?.snapshot().coherent);expect((await data(page)).outcomes[0].status).toBe('archived');
});
test('native keyboard, contrast, targets, 360px zoom geometry and captures',async({page},info)=>{
 await open(page);await page.emulateMedia({reducedMotion:'reduce'});const summary=page.locator('#outcomeImportancePanel summary');await summary.scrollIntoViewIfNeeded();await summary.focus();await expect(summary).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#outcomeImportancePanel')).toHaveAttribute('open','');await page.keyboard.press('Space');await expect(page.locator('#outcomeImportancePanel')).not.toHaveAttribute('open','');await page.keyboard.press('Enter');await expect(page.locator('#outcomeImportanceChoice')).toHaveAccessibleName('Isso continua importante para você?');await choose(page,'yes');await summary.focus();expect(await contrast(summary)).toBeGreaterThanOrEqual(4.5);expect(await contrast(summary,'outlineColor')).toBeGreaterThanOrEqual(3);expect(await contrast(action(page))).toBeGreaterThanOrEqual(4.5);for(const l of [summary,action(page),page.locator('#outcomeImportanceChoice')])expect((await l.boundingBox()).height).toBeGreaterThanOrEqual(44);
 await fs.mkdir('test-results',{recursive:true});await page.screenshot({path:`test-results/importance-${info.project.name}.png`});await page.setViewportSize({width:360,height:900});await page.evaluate(()=>document.body.style.zoom='2');await action(page).evaluate(b=>{b.style.fontFamily='monospace';b.style.fontSize='16px'});for(const value of ['yes','partial','no']){await choose(page,value);const widths=await action(page).evaluate(b=>{const s=getComputedStyle(b),ctx=document.createElement('canvas').getContext('2d');ctx.font=s.font;return{available:b.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),required:Math.max(...b.textContent.split(/\s+/).map(w=>ctx.measureText(w).width))}});expect(widths.available).toBeGreaterThanOrEqual(widths.required);for(const l of [page.locator('#learningOutcomeDialog'),action(page),page.locator('#outcomeImportanceChoice')]){const box=await l.boundingBox();expect(box.x).toBeGreaterThanOrEqual(-1);expect(box.x+box.width).toBeLessThanOrEqual(361)}}const dialogBox=await page.locator('#learningOutcomeDialog').boundingBox();expect(dialogBox.y).toBeGreaterThanOrEqual(-1);expect(dialogBox.y+dialogBox.height).toBeLessThanOrEqual(901);for(const l of [page.locator('#outcomeImportanceChoice'),action(page)]){await l.scrollIntoViewIfNeeded();await l.focus();await expect(l).toBeFocused();const b=await l.boundingBox();expect(b.y).toBeGreaterThanOrEqual(-1);expect(b.y+b.height).toBeLessThanOrEqual(901);expect(await l.evaluate(e=>{const b=e.getBoundingClientRect();return e.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2))})).toBe(true)}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`test-results/importance-zoom-${info.project.name}.png`});
});
