const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function open(page,{fallback=false}={}){
 await page.route(/^https?:\/(?!\/127\.0\.0\.1)/,route=>route.abort());
 await page.addInitScript(({fallback})=>{localStorage.setItem('compasso.ux.mode.v1','advanced');if(fallback)Object.defineProperty(window,'indexedDB',{value:undefined,configurable:true});globalThis.CompassoDriveSync||={prepareLocalState(input){return{data:structuredClone(input),baseline:new Map()}},activateLocalState(){}}},{fallback});
 await page.goto('/?view=weekly',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>globalThis.CompassoFeatures?.installed&&globalThis.CompassoWeeklyFrictionModel&&globalThis.CompassoPwaLifecycle?.snapshot().coherent);
 await page.evaluate(async()=>{state.data.weeklyReviews=[];state.data.learningOutcomes=[];state.data.learningSignals=[];state.data.executionSessions=[];state.data.evidence=[];await CompassoStorage.save('compasso.app.v1',state.data);renderAll()});
}
async function createCapability(page,title='Comparar estratégias'){
 await page.evaluate(()=>CompassoInformationArchitecture.open('capabilities'));await page.locator('[data-outcome-new]').first().click();await page.locator('[name="capability"]').fill(title);await page.locator('[name="nextAttempt"]').fill('Comparar dois planos');await page.locator('#learningOutcomeForm').evaluate(form=>form.requestSubmit());await expect(page.locator('#learningOutcomeDialog')).toBeHidden();
 const outcome=await page.evaluate(()=>structuredClone(state.data.learningOutcomes[0]));await page.evaluate(()=>{CompassoInformationArchitecture.open('weekly');renderAll()});return outcome;
}
async function answer(page,{task='Comparar os planos',reason='unclear',adjustment='Ler um plano por cinco minutos'}={}){
 await page.locator('#weeklyFriction').evaluate(details=>details.open=true);await page.locator('#weeklyFrictionTask').fill(task);await page.locator('#weeklyFrictionReason').selectOption(reason);await page.locator('#weeklyFrictionAdjustment').fill(adjustment);
}
async function submit(page){await page.locator('#weeklyReviewForm').evaluate(form=>form.requestSubmit())}
async function data(page){return page.evaluate(()=>structuredClone({reviews:state.data.weeklyReviews,outcomes:state.data.learningOutcomes,experiments:state.data.behavioralExperiments,signals:state.data.learningSignals}))}
async function apply(page){await page.locator('#weeklyFrictionApply').click()}
async function contrast(locator,property='color'){
  return locator.evaluate((node,property)=>{
    const lum=c=>{const [r,g,b]=c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>{const x=n/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*r+.7152*g+.0722*b};
    let background='rgb(255,255,255)';for(let e=node;e;e=e.parentElement){const c=getComputedStyle(e).backgroundColor;if(!c.startsWith('rgba')||!c.endsWith(', 0)')){background=c;break}}
    const x=lum(getComputedStyle(node)[property]),y=lum(background);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);
  },property);
}


test('opcional e progressivo; vazio salva sem campos novos ou inferência',async({page})=>{
 await open(page);await expect(page.locator('#weeklyFriction')).not.toHaveAttribute('open','');await expect(page.locator('#weeklyFrictionFollowup')).toBeHidden();const before=await data(page);
 await page.locator('#weeklyFriction summary').click();expect(await data(page)).toEqual(before);await answer(page);await expect(page.locator('#weeklyFrictionFollowup')).toBeVisible();await page.locator('#weeklyFrictionTask').fill('');await expect(page.locator('#weeklyFrictionFollowup')).toBeHidden();await expect(page.locator('#weeklyFrictionAdjustment')).toHaveValue('');await expect(page.locator('#weeklyFrictionReason')).toHaveValue('');await submit(page);
 await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);const review=(await data(page)).reviews[0];expect(review.schemaVersion).toBe(2);expect(review.blockers).toBe('');expect(Object.keys(review).some(key=>/friction|procrastination/i.test(key))).toBe(false);
});
test('aplica texto preservando anteriores, sem duplicar nem salvar até concluir',async({page})=>{
 await open(page);await page.locator('#weeklyBlockers').fill('Bloqueio antigo');await page.locator('#weeklyDecision').fill('Decisão antiga');await answer(page);const before=await data(page);await apply(page);
 await expect(page.locator('#weeklyDecision')).toBeFocused();expect(await data(page)).toEqual(before);const blockers=await page.locator('#weeklyBlockers').inputValue(),decision=await page.locator('#weeklyDecision').inputValue();expect(blockers).toContain('Bloqueio antigo');expect(blockers).toContain('Primeiro passo pouco claro');await apply(page);await expect(page.locator('#weeklyBlockers')).toHaveValue(blockers);await expect(page.locator('#weeklyDecision')).toHaveValue(decision);
 await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>CompassoFeatures?.installed);await expect(page.locator('#weeklyBlockers')).toHaveValue(blockers);await expect(page.locator('#weeklyDecision')).toHaveValue(decision);await expect(page.locator('#weeklyFrictionTask')).toHaveValue('');
});
test('rascunho pendente exige aplicar ou limpar; navegação e reload não o persistem',async({page})=>{
 await open(page);await answer(page);await submit(page);await expect(page.locator('#weeklyFrictionError')).toBeVisible();await expect(page.locator('#weeklyFrictionAdjustment')).toBeFocused();expect((await data(page)).reviews).toEqual([]);
 await page.locator('#weeklyFrictionClear').click();await expect(page.locator('#weeklyFrictionTask')).toBeFocused();await expect(page.locator('#weeklyFrictionFollowup')).toBeHidden();await answer(page);await page.locator('[data-week-nav="-1"]').click();await expect(page.locator('#weeklyFrictionTask')).toHaveValue('');await expect(page.locator('#weeklyFriction')).not.toHaveAttribute('open','');await page.locator('[data-week-current]').click();await answer(page);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>CompassoFeatures?.installed);await expect(page.locator('#weeklyFrictionTask')).toHaveValue('');expect((await data(page)).reviews).toEqual([]);
});
test('capacidade sem execução entra na decisão atual e salva tentativa/reflexão juntas',async({page})=>{
 await open(page);const original=await createCapability(page);const before=await data(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(original.id);await apply(page);
 const card=page.locator(`[data-weekly-capability="${original.id}"]`);await expect(card).toContainText('Selecionada nesta revisão');await expect(card.locator('[data-weekly-decision]')).toHaveValue('revise');await expect(card.locator('[data-weekly-attempt]')).toBeFocused();expect(await data(page)).toEqual(before);
 await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.learningOutcomes[0].nextAttempt.text)).toBe('Ler um plano por cinco minutos');const saved=await data(page);expect(saved.outcomes[0].nextAttempt.id).toBe(original.nextAttempt.id);expect(saved.reviews[0].capabilityReflections[0]).toMatchObject({decision:'revise',decidedAttemptText:'Ler um plano por cinco minutos'});expect(saved.experiments).toEqual(before.experiments);expect(saved.signals).toEqual(before.signals);
});
test('incluir outra capacidade preserva decisões e textos de todos os cartões',async({page})=>{
 await open(page);const first=await createCapability(page,'Primeira capacidade'),second=await createCapability(page,'Segunda capacidade');await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(first.id);await apply(page);const card=page.locator(`[data-weekly-capability="${first.id}"]`);await card.locator('[data-weekly-reflection]').fill('Reflexão manual');await card.locator('[data-weekly-attempt]').fill('Rascunho manual');await card.locator('[data-weekly-future-use]').selectOption('explain');
 await page.locator('#weeklyFrictionTarget').selectOption(second.id);await page.locator('#weeklyFrictionAdjustment').fill('Resolver um exemplo');await apply(page);await expect(card.locator('[data-weekly-reflection]')).toHaveValue('Reflexão manual');await expect(card.locator('[data-weekly-attempt]')).toHaveValue('Rascunho manual');await expect(card.locator('[data-weekly-future-use]')).toHaveValue('explain');await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);expect((await data(page)).reviews[0].capabilityReflections).toHaveLength(2);
});
test('limites e alvo stale bloqueiam sem apagar texto nem sobrescrever capacidade',async({page})=>{
 await open(page);const outcome=await createCapability(page);await answer(page,{adjustment:''});await apply(page);await expect(page.locator('#weeklyFrictionAdjustment')).toBeFocused();await page.locator('#weeklyFrictionAdjustment').fill('Ler um exemplo');await page.locator('#weeklyBlockers').fill('b'.repeat(600));await apply(page);await expect(page.locator('#weeklyBlockers')).toHaveValue('b'.repeat(600));await expect(page.locator('#weeklyFrictionError')).toContainText('600');await expect(page.locator('#weeklyBlockers')).toHaveAttribute('aria-invalid','true');
 await page.locator('#weeklyBlockers').fill('Texto seguro');await page.locator('#weeklyDecision').fill('d'.repeat(600));await apply(page);await expect(page.locator('#weeklyDecision')).toHaveAttribute('aria-invalid','true');await expect(page.locator('#weeklyBlockers')).not.toHaveAttribute('aria-invalid','true');await page.locator('#weeklyFrictionClear').click();await expect(page.locator('#weeklyDecision')).not.toHaveAttribute('aria-invalid','true');await page.locator('#weeklyDecision').fill('');await answer(page,{adjustment:'Ler um exemplo'});
 await page.locator('#weeklyBlockers').fill('Texto seguro');await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await page.evaluate(()=>state.data.learningOutcomes[0].nextAttempt.text='Mudança externa');const before=await data(page);await apply(page);await expect(page.locator('#weeklyFrictionError')).toContainText('capacidade mudou');expect(await data(page)).toEqual(before);await expect(page.locator('#weeklyBlockers')).toHaveValue('Texto seguro');
});
test('alvo alterado depois de aplicar impede save sem sobrescrever',async({page})=>{
 await open(page);const outcome=await createCapability(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);await page.evaluate(()=>state.data.learningOutcomes[0].status='archived');const before=await data(page);await submit(page);await expect(page.locator('#weeklyFrictionError')).toContainText('capacidade mudou');expect(await data(page)).toEqual(before);
});
test('falha de persistência repõe todo o rascunho e retry salva uma única revisão',async({page})=>{
 await open(page);const outcome=await createCapability(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);const before=await data(page);await page.evaluate(()=>{window.__storage=CompassoStorage;window.CompassoStorage=Object.freeze({...CompassoStorage,save:async()=>false})});await submit(page);await expect(page.locator('#weeklyReviewMeta')).toBeFocused();expect(await data(page)).toEqual(before);await expect(page.locator('[data-weekly-attempt]')).toHaveValue('Ler um plano por cinco minutos');expect(await page.locator('#weeklyDecision').inputValue()).toContain('Ler um plano');
 await page.evaluate(()=>window.CompassoStorage=window.__storage);await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);expect((await data(page)).outcomes[0].nextAttempt.text).toBe('Ler um plano por cinco minutos');
});
for(const fallback of [false,true])test(`backup/restore e offline preservam os campos existentes em ${fallback?'fallback':'IndexedDB'}`,async({page,context})=>{
 await open(page,{fallback});const outcome=await createCapability(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);const before=await data(page);
 await page.locator('#settingsBtn').click();page.once('dialog',dialog=>dialog.accept());const downloading=page.waitForEvent('download');await page.locator('#exportBtn').click();const download=await downloading;await page.locator('#importInput').setInputFiles(await download.path());await page.locator('#restoreConfirmBtn').click();await expect(page.locator('#restoreDialog')).toBeHidden();expect(await data(page)).toEqual(before);
 await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>CompassoFeatures?.installed&&CompassoWeeklyFrictionModel);expect(await data(page)).toEqual(before);await expect(page.locator('#weeklyDecision')).toHaveValue(before.reviews[0].decision);
});
test('teclado, foco, alvos, 360px e zoom200% mantêm a ajuda utilizável',async({page},info)=>{
 await open(page);await page.emulateMedia({reducedMotion:'reduce'});const summary=page.locator('#weeklyFriction summary');await summary.scrollIntoViewIfNeeded();await summary.focus();await expect(summary).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#weeklyFriction')).toHaveAttribute('open','');await page.keyboard.press('Space');await expect(page.locator('#weeklyFriction')).not.toHaveAttribute('open','');await page.keyboard.press('Enter');await answer(page);
 for(const selector of ['#weeklyFrictionApply','#weeklyFrictionClear','#weeklyFrictionReason','#weeklyFrictionTarget'])expect((await page.locator(selector).boundingBox()).height).toBeGreaterThanOrEqual(44);
 await summary.focus();expect(await contrast(summary)).toBeGreaterThanOrEqual(4.5);expect(await contrast(summary,'outlineColor')).toBeGreaterThanOrEqual(3);for(const button of await page.locator('#weeklyFriction button').all())expect(await contrast(button)).toBeGreaterThanOrEqual(4.5);
 expect(await summary.evaluate(e=>parseFloat(getComputedStyle(e).outlineWidth))).toBeGreaterThanOrEqual(3);
 await fs.mkdir('test-results',{recursive:true});await summary.scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/weekly-friction-${info.project.name}.png`});await page.setViewportSize({width:360,height:900});await page.evaluate(()=>document.body.style.zoom='2');await page.locator('#weeklyFrictionApply').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.locator('#weeklyFriction button').evaluateAll(buttons=>buttons.forEach(button=>{button.style.fontFamily='monospace';button.style.fontSize='16px'}));
 const widths=await page.locator('#weeklyFriction button').evaluateAll(buttons=>buttons.map(button=>{const style=getComputedStyle(button),ctx=document.createElement('canvas').getContext('2d');ctx.font=style.font;return{available:button.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),required:Math.max(...button.textContent.split(/\s+/).map(word=>ctx.measureText(word).width))}}));for(const width of widths)expect(width.available).toBeGreaterThanOrEqual(width.required);
 await page.screenshot({path:`test-results/weekly-friction-zoom-${info.project.name}.png`});await page.evaluate(()=>document.body.style.zoom='1');await page.locator('#weeklyFrictionApply').focus();await page.keyboard.press('Enter');await expect(page.locator('#weeklyDecision')).toBeFocused();
});

test('rerender da mesma semana conserva aplicação e edits manuais antes do save',async({page})=>{
 await open(page);const outcome=await createCapability(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);await page.locator('#weeklyWins').fill('Um avanço manual');await page.locator('[data-weekly-reflection]').fill('Reflexão manual');await page.locator('[data-weekly-attempt]').fill('Ajuste editado manualmente');await page.evaluate(()=>renderAll());
 await expect(page.locator('#weeklyWins')).toHaveValue('Um avanço manual');expect(await page.locator('#weeklyBlockers').inputValue()).toContain('Comparar os planos');await expect(page.locator('[data-weekly-reflection]')).toHaveValue('Reflexão manual');await expect(page.locator('[data-weekly-attempt]')).toHaveValue('Ajuste editado manualmente');await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);expect((await data(page)).outcomes[0].nextAttempt.text).toBe('Ajuste editado manualmente');
});
test('seleção explícita usa tentativa atual sem reescrever execução histórica',async({page})=>{
 await open(page);const outcome=await createCapability(page);await page.evaluate(async()=>{
  const outcome=state.data.learningOutcomes[0],now=new Date().toISOString();state.data.executionSessions=[{id:'historical-friction',source:{collection:'sessions',id:'historical-friction'},mode:'quick',status:'completed',domain:'learningOutcome',itemId:outcome.id,learningContext:{outcomeId:outcome.id,attemptId:'old-attempt-id',attemptText:'Tentativa histórica'},startedAt:now,endedAt:now,durationMs:60000,updatedAt:now}];await CompassoStorage.save('compasso.app.v1',state.data);renderAll();
 });const before=await page.evaluate(()=>structuredClone(state.data.executionSessions));await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);await expect(page.locator('[data-weekly-decision]')).toHaveValue('revise');await submit(page);await expect.poll(()=>page.evaluate(()=>state.data.weeklyReviews.length)).toBe(1);expect(await page.evaluate(()=>state.data.executionSessions)).toEqual(before);
});
test('KEEP explícito preserva tentativa apesar do texto de ajuste e save em voo bloqueia reentrada',async({page})=>{
 await open(page);const outcome=await createCapability(page);await answer(page);await page.locator('#weeklyFrictionTarget').selectOption(outcome.id);await apply(page);await page.locator('[data-weekly-decision]').selectOption('keep');await page.evaluate(()=>{window.__storage=CompassoStorage;window.__saveCalls=0;window.CompassoStorage=Object.freeze({...CompassoStorage,save:async(...args)=>{window.__saveCalls++;await new Promise(resolve=>window.__releaseSave=resolve);return window.__storage.save(...args)}})});
 await submit(page);await expect(page.locator('#weeklyFrictionApply')).toBeDisabled();await submit(page);expect(await page.evaluate(()=>window.__saveCalls)).toBe(1);await page.evaluate(()=>window.__releaseSave());await expect(page.locator('#weeklyReviewForm')).toHaveAttribute('aria-busy','false');expect((await data(page)).outcomes[0]).toEqual(outcome);expect((await data(page)).reviews[0].capabilityReflections[0].decision).toBe('keep');
});
