(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.CompassoContingencyModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const clean=(v,n=240)=>typeof v==='string'?v.trim().slice(0,n):'';
  function normalizeMinimum(v){if(!v||typeof v!=='object')return null;const x={description:clean(v.description),estimatedMinutes:Math.max(0,Math.min(1440,Math.round(Number(v.estimatedMinutes)||0)))||null,completionCriterion:clean(v.completionCriterion),countsAsComplete:v.countsAsComplete===true};return x.description||x.estimatedMinutes||x.completionCriterion?x:null;}
  function normalizeContingency(v,i=0,now=new Date().toISOString()){if(!v||typeof v!=='object')return null;const condition=clean(v.condition),response=clean(v.response);if(!condition&&!response)return null;return{id:clean(v.id,80)||`c${Date.now()}${i}`,condition,response,enabled:v.enabled!==false,order:Number.isFinite(Number(v.order))?Number(v.order):i,createdAt:v.createdAt||now,updatedAt:v.updatedAt||v.createdAt||now};}
  function normalizeAction(item,now=new Date().toISOString()){if(!item||typeof item!=='object')return item;item.minimumVersion=normalizeMinimum(item.minimumVersion);const seen=new Set();item.contingencies=(Array.isArray(item.contingencies)?item.contingencies:[]).map((x,i)=>normalizeContingency(x,i,now)).filter(x=>x&&!seen.has(x.id)&&seen.add(x.id)).sort((a,b)=>a.order-b.order).map((x,i)=>({...x,order:i}));return item;}
  function upsert(list,value,now=new Date().toISOString()){const out=(Array.isArray(list)?list:[]).map((x,i)=>normalizeContingency(x,i,now)).filter(Boolean);const entry=normalizeContingency(value,out.length,now);if(!entry)return out;const i=out.findIndex(x=>x.id===entry.id);if(i>=0)out[i]={...out[i],...entry,createdAt:out[i].createdAt,updatedAt:now};else out.push(entry);return out.sort((a,b)=>a.order-b.order).map((x,j)=>({...x,order:j}));}
  const remove=(list,id)=>(Array.isArray(list)?list:[]).filter(x=>x?.id!==id).map((x,i)=>({...x,order:i}));
  function move(list,id,d){const out=(Array.isArray(list)?list:[]).slice().sort((a,b)=>a.order-b.order),i=out.findIndex(x=>x.id===id);if(i<0)return out;const j=Math.max(0,Math.min(out.length-1,i+d));const[x]=out.splice(i,1);out.splice(j,0,x);return out.map((v,k)=>({...v,order:k}));}
  const variant=(kind,id=null)=>({kind:['ideal','minimum','contingency'].includes(kind)?kind:'ideal',contingencyId:kind==='contingency'?id:null});
  return{VERSION:1,normalizeMinimum,normalizeContingency,normalizeAction,upsert,remove,move,variant};
});
