/* Compasso · Planejado vs. realizado e síntese orientada de livros
 * Fase 2.4: fecha o ciclo semanal e transforma leitura em compreensão estruturada.
 */

const OUTCOMES_FEATURE_VERSION = 1;
state.data.bookSyntheses = Array.isArray(state.data.bookSyntheses) ? state.data.bookSyntheses : [];
labels.outcomes = { title: 'Resultados', kicker: 'Planejado vs. realizado' };
const outcomesRuntime = { weekOffset: 0, selectedBookId: null };

function outcomesSyntheses() { state.data.bookSyntheses = Array.isArray(state.data.bookSyntheses) ? state.data.bookSyntheses : []; return state.data.bookSyntheses; }
function outcomesWeekRange(offset = 0) { const now = new Date(), day = (now.getDay() + 6) % 7, start = new Date(now.getFullYear(), now.getMonth(), now.getDate() - day + offset * 7), end = new Date(start.getFullYear(), start.getMonth(), start.getDate() + 7); return { start, end, key: start.toISOString().slice(0,10) }; }
function outcomesDateKey(value) { if (!value) return ''; const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0,10); }
function outcomesInRange(value, range) { const date = new Date(value); return date >= range.start && date < range.end; }
function outcomesDuration(ms) { const minutes = Math.round(positiveNumber(ms) / 60000), hours = Math.floor(minutes / 60), rest = minutes % 60; return hours ? `${hours}h ${String(rest).padStart(2,'0')}min` : `${minutes} min`; }
function outcomesWeekData(range) {
  const plans = (state.data.dailyPlans || []).filter(plan => { const date = new Date(`${plan.date}T12:00:00`); return date >= range.start && date < range.end; });
  const sessions = (state.data.sessions || []).filter(session => session.status === 'completed' && outcomesInRange(session.endedAt || session.startedAt, range));
  const evidence = (state.data.evidence || []).filter(item => outcomesInRange(item.createdAt, range));
  const planned = plans.reduce((sum, plan) => sum + (plan.items || []).length, 0), completed = plans.reduce((sum, plan) => sum + (plan.items || []).filter(item => item.completedAt).length, 0);
  const days = Array.from({ length:7 }, (_, index) => { const date = new Date(range.start.getFullYear(), range.start.getMonth(), range.start.getDate() + index), key = outcomesDateKey(date), plan = plans.find(item => item.date === key), daySessions = sessions.filter(session => outcomesDateKey(session.endedAt || session.startedAt) === key); return { date, planned:(plan?.items || []).length, completed:(plan?.items || []).filter(item => item.completedAt).length, sessions:daySessions.length, durationMs:daySessions.reduce((sum, session) => sum + positiveNumber(session.durationMs), 0) }; });
  return { plans, sessions, evidence, planned, completed, completion:planned ? Math.round(completed/planned*100) : 0, durationMs:sessions.reduce((sum, session) => sum + positiveNumber(session.durationMs), 0), days };
}
function outcomesSynthesis(bookId) { return outcomesSyntheses().find(item => item.bookId === bookId) || null; }
function outcomesBook() { const books = state.data.reading || []; if (!outcomesRuntime.selectedBookId || !books.some(book => book.id === outcomesRuntime.selectedBookId)) outcomesRuntime.selectedBookId = books[0]?.id || null; return books.find(book => book.id === outcomesRuntime.selectedBookId) || null; }
function outcomesMarkdown(book, synthesis) { return `# Síntese — ${book.title}\n\n## Fonte\n- Livro: ${book.title}\n- Contexto: ${book.meta || ''}\n- Progresso: ${clamp(book.progress)}%\n\n## Problema central\n${synthesis.centralProblem}\n\n## Tese ou ideia central\n${synthesis.thesis}\n\n## Conceitos-chave\n${synthesis.keyConcepts}\n\n## Estrutura do argumento\n${synthesis.argument}\n\n## Avaliação crítica\n${synthesis.evaluation}\n\n## Aplicações\n${synthesis.applications}\n\n## Perguntas abertas\n${synthesis.openQuestions}\n`; }

function outcomesInstallStyles() {
  if (document.getElementById('compassoOutcomesStyles')) return;
  const style = document.createElement('style'); style.id = 'compassoOutcomesStyles'; style.textContent = `
    .outcomes-shell{display:grid;gap:18px}.outcomes-hero{background:#302f2a;color:#fff;border-radius:22px;padding:27px 29px;display:flex;align-items:flex-end;justify-content:space-between;gap:24px;box-shadow:var(--shadow)}.outcomes-hero .eyebrow{color:#aaa79f}.outcomes-hero h2{margin:8px 0 7px;font:800 clamp(24px,3vw,36px)/1.15 Manrope,sans-serif;letter-spacing:-.05em}.outcomes-hero p{margin:0;color:#bbb8b0;font-size:12px;line-height:1.6}.outcomes-week-nav{display:flex;gap:7px;flex-wrap:wrap}.outcomes-week-nav button{border:1px solid #4b4a44;background:#3a3934;color:#fff;border-radius:9px;min-height:37px;padding:0 12px;font-size:10px;font-weight:800;cursor:pointer}.outcomes-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.outcomes-kpi,.outcomes-panel{background:var(--surface-strong);border:1px solid var(--line);border-radius:16px;padding:17px;box-shadow:var(--shadow)}.outcomes-kpi span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.outcomes-kpi strong{display:block;margin-top:8px;font:800 22px/1 Manrope,sans-serif}.outcomes-kpi small{display:block;margin-top:6px;color:var(--muted);font-size:9px}.outcomes-panel{border-radius:18px;padding:21px}.outcomes-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:15px}.outcomes-panel-head h3{margin:4px 0 0;font:800 17px/1.25 Manrope,sans-serif}.outcomes-panel-head p{margin:5px 0 0;color:var(--muted);font-size:10px}.outcomes-days{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.outcomes-day{border:1px solid var(--line);border-radius:12px;padding:11px}.outcomes-day>span{display:block;color:var(--muted);font-size:8px;text-transform:uppercase}.outcomes-day>strong{display:block;margin-top:6px;font-size:16px}.outcomes-day p{margin:6px 0 0;color:var(--muted);font-size:8px;line-height:1.45}.outcomes-day .progress{margin-top:9px}.synthesis-form{display:grid;gap:15px}.synthesis-book-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px}.synthesis-book-row select{width:100%;border:1px solid var(--line);border-radius:10px;background:#fff;padding:11px 12px}.synthesis-status{padding:7px 10px;border-radius:999px;background:var(--violet-soft);color:var(--violet);font-size:9px;font-weight:800;align-self:center}.synthesis-status.completed{background:var(--green-soft);color:var(--green)}.synthesis-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.synthesis-form .field label{display:block;font-size:10px;font-weight:800;margin-bottom:7px}.synthesis-form textarea{width:100%;min-height:110px;border:1px solid var(--line);border-radius:10px;background:#fff;padding:11px 12px;resize:vertical;line-height:1.5}.synthesis-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.outcomes-empty{border:1px dashed var(--line);border-radius:12px;padding:26px;text-align:center;color:var(--muted);font-size:11px}
    @media(max-width:1050px){.outcomes-kpis{grid-template-columns:repeat(3,1fr)}.outcomes-days{grid-template-columns:repeat(4,1fr)}}@media(max-width:720px){.outcomes-hero{align-items:flex-start;flex-direction:column}.outcomes-kpis{grid-template-columns:1fr 1fr}.outcomes-days{grid-template-columns:1fr 1fr}.synthesis-grid{grid-template-columns:1fr}.synthesis-book-row{grid-template-columns:1fr}.outcomes-panel{padding:17px}}
  `; document.head.appendChild(style);
}
function outcomesInstallUi() {
  if (!document.querySelector('[data-view="outcomes"]')) { const weaknessNav = document.querySelector('[data-view="weakness"]'); weaknessNav?.insertAdjacentHTML('afterend', `<button class="nav-item" data-view="outcomes">${icon('spark')}<span>Resultados</span><span class="nav-badge" id="outcomesBadge"></span></button>`); }
  if (!document.getElementById('outcomesView')) document.querySelector('.content')?.insertAdjacentHTML('beforeend', `<section class="view" id="outcomesView"><div class="outcomes-shell"><section class="outcomes-hero"><div><div class="eyebrow">Fechamento do ciclo</div><h2>Planejar é hipótese.<br>Realizar é evidência.</h2><p>Compare intenção e execução; depois transforme leitura em uma síntese que você consegue avaliar e aplicar.</p></div><div class="outcomes-week-nav"><button data-outcomes-week="-1">← Semana anterior</button><button data-outcomes-current>Semana atual</button><button data-outcomes-week="1" id="outcomesNextWeek">Próxima →</button></div></section><div class="outcomes-kpis" id="outcomesKpis"></div><section class="outcomes-panel"><div class="outcomes-panel-head"><div><div class="eyebrow">Planejado vs. realizado</div><h3 id="outcomesWeekTitle"></h3><p>Conclusão de ações e execução registrada em sessões.</p></div></div><div class="outcomes-days" id="outcomesDays"></div></section><section class="outcomes-panel"><div class="outcomes-panel-head"><div><div class="eyebrow">Leitura analítica</div><h3>Síntese orientada de livros</h3><p>Separe o que o autor afirma, como argumenta e sua avaliação.</p></div></div><div id="synthesisWorkspace"></div></section></div></section>`);
}

function renderOutcomesWeek() {
  const range = outcomesWeekRange(outcomesRuntime.weekOffset), data = outcomesWeekData(range), endLabel = new Date(range.end.getTime()-86400000), format = new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'});
  document.getElementById('outcomesWeekTitle').textContent = `${format.format(range.start)} — ${format.format(endLabel)}`; document.getElementById('outcomesNextWeek').disabled = outcomesRuntime.weekOffset >= 0;
  const kpis = [{label:'Ações planejadas',value:data.planned,note:'itens no plano diário'},{label:'Ações concluídas',value:data.completed,note:`${data.completion}% de conclusão`},{label:'Sessões',value:data.sessions.length,note:'execuções registradas'},{label:'Tempo focado',value:outcomesDuration(data.durationMs),note:'sem pausas'},{label:'Evidências',value:data.evidence.length,note:'resultados verificáveis'}];
  document.getElementById('outcomesKpis').innerHTML = kpis.map(item => `<article class="outcomes-kpi"><span>${item.label}</span><strong>${item.value}</strong><small>${item.note}</small></article>`).join('');
  document.getElementById('outcomesDays').innerHTML = data.days.map(day => { const rate = day.planned ? Math.round(day.completed/day.planned*100) : 0; return `<article class="outcomes-day"><span>${new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit'}).format(day.date)}</span><strong>${day.completed}/${day.planned}</strong><p>${day.sessions} sessões · ${outcomesDuration(day.durationMs)}</p><div class="progress"><span style="width:${rate}%"></span></div></article>`; }).join('');
  document.getElementById('outcomesBadge').textContent = data.planned && data.completed < data.planned ? data.planned-data.completed : '';
}
function renderSynthesis() {
  const books = state.data.reading || [], workspace = document.getElementById('synthesisWorkspace'); if (!books.length) { workspace.innerHTML = '<div class="outcomes-empty">Adicione uma leitura para criar uma síntese.</div>'; return; }
  const book = outcomesBook(), synthesis = outcomesSynthesis(book.id) || {}, options = books.map(item => `<option value="${item.id}" ${item.id===book.id?'selected':''}>${escapeHtml(item.title)}</option>`).join('');
  workspace.innerHTML = `<form class="synthesis-form" id="synthesisForm"><div class="synthesis-book-row"><select id="synthesisBook">${options}</select><span class="synthesis-status ${synthesis.status==='completed'?'completed':''}">${synthesis.status==='completed'?'Síntese concluída':'Rascunho'}</span></div><div class="synthesis-grid"><div class="field"><label for="synthesisProblem">Problema central</label><textarea id="synthesisProblem" placeholder="Que problema ou pergunta o livro tenta resolver?">${escapeHtml(synthesis.centralProblem||'')}</textarea></div><div class="field"><label for="synthesisThesis">Tese ou ideia central</label><textarea id="synthesisThesis" placeholder="O que o autor afirma?">${escapeHtml(synthesis.thesis||'')}</textarea></div><div class="field"><label for="synthesisConcepts">Conceitos-chave</label><textarea id="synthesisConcepts" placeholder="Termos que sustentam a obra.">${escapeHtml(synthesis.keyConcepts||'')}</textarea></div><div class="field"><label for="synthesisArgument">Estrutura do argumento</label><textarea id="synthesisArgument" placeholder="Como o autor chega à conclusão?">${escapeHtml(synthesis.argument||'')}</textarea></div><div class="field"><label for="synthesisEvaluation">Avaliação crítica</label><textarea id="synthesisEvaluation" placeholder="O argumento é convincente? Quais limites?">${escapeHtml(synthesis.evaluation||'')}</textarea></div><div class="field"><label for="synthesisApplications">Aplicações</label><textarea id="synthesisApplications" placeholder="Como testar ou aplicar as ideias?">${escapeHtml(synthesis.applications||'')}</textarea></div><div class="field"><label for="synthesisQuestions">Perguntas abertas</label><textarea id="synthesisQuestions" placeholder="O que ainda precisa ser investigado?">${escapeHtml(synthesis.openQuestions||'')}</textarea></div></div><div class="synthesis-actions"><button class="quiet-btn" type="button" data-synthesis-note>Gerar nota Markdown</button><button class="secondary-btn" type="submit">Salvar rascunho</button><button class="primary-btn" type="button" data-synthesis-complete>${icon('check')}Concluir síntese</button></div></form>`;
  document.getElementById('synthesisBook').addEventListener('change', event => { outcomesRuntime.selectedBookId = event.target.value; renderSynthesis(); });
  document.getElementById('synthesisForm').addEventListener('submit', event => { event.preventDefault(); saveSynthesis(false); });
}
function synthesisPayload(status) { return { centralProblem:document.getElementById('synthesisProblem').value.trim(), thesis:document.getElementById('synthesisThesis').value.trim(), keyConcepts:document.getElementById('synthesisConcepts').value.trim(), argument:document.getElementById('synthesisArgument').value.trim(), evaluation:document.getElementById('synthesisEvaluation').value.trim(), applications:document.getElementById('synthesisApplications').value.trim(), openQuestions:document.getElementById('synthesisQuestions').value.trim(), status, updatedAt:new Date().toISOString() }; }
function saveSynthesis(complete) { const book = outcomesBook(); if (!book) return null; const existing = outcomesSynthesis(book.id), payload = synthesisPayload(complete?'completed':existing?.status||'draft'); if (complete && (!payload.centralProblem || !payload.thesis || !payload.argument || !payload.evaluation)) { showToast('Preencha problema, tese, argumento e avaliação'); return null; } if (existing) Object.assign(existing,payload); else outcomesSyntheses().unshift({id:`syn${Date.now()}`,schemaVersion:OUTCOMES_FEATURE_VERSION,bookId:book.id,noteId:null,createdAt:new Date().toISOString(),...payload}); saveData(complete?'Síntese concluída':'Síntese salva'); return outcomesSynthesis(book.id); }
function generateSynthesisNote() { let synthesis = saveSynthesis(false); const book = outcomesBook(); if (!synthesis || !book) return; let note = synthesis.noteId ? state.data.notes.find(item => item.id===synthesis.noteId) : null; if (!note) { const folder = state.data.folders.find(item => item.id==='f-reading-current') || state.data.folders.find(item => item.domain==='reading') || state.data.folders[0]; note = {id:`n${Date.now()}`,title:`Síntese — ${book.title}`,folder:folder?.id||null,domain:'reading',linkedItemId:book.id,tags:['síntese','leitura-analítica'],updated:new Date().toISOString().slice(0,10),content:''}; state.data.notes.push(note); synthesis.noteId=note.id; } note.title=`Síntese — ${book.title}`; note.content=outcomesMarkdown(book,synthesis); note.updated=new Date().toISOString().slice(0,10); saveData('Nota de síntese atualizada no Atlas'); }

outcomesInstallStyles(); outcomesInstallUi(); const renderAllWithoutOutcomes = renderAll; renderAll = function(){ renderAllWithoutOutcomes(); renderOutcomesWeek(); renderSynthesis(); };
document.addEventListener('click', event => { const week=event.target.closest('[data-outcomes-week]'); if(week){ outcomesRuntime.weekOffset=Math.min(0,outcomesRuntime.weekOffset+Number(week.dataset.outcomesWeek)); renderOutcomesWeek(); } if(event.target.closest('[data-outcomes-current]')){ outcomesRuntime.weekOffset=0; renderOutcomesWeek(); } if(event.target.closest('[data-synthesis-complete]')) saveSynthesis(true); if(event.target.closest('[data-synthesis-note]')) generateSynthesisNote(); });
