(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.CompassoRitualModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const clean=(v,n=240)=>typeof v==='string'?v.trim().slice(0,n):'';
  const TYPES=['study','programming','reading','writing','planning'];
  function items(v){return(Array.isArray(v)?v:[]).map((x,i)=>({id:clean(x?.id,80)||`i${i}`,text:clean(x?.text||x),required:x?.required!==false,order:Number.isFinite(Number(x?.order))?Number(x.order):i})).filter(x=>x.text).sort((a,b)=>a.order-b.order).map((x,i)=>({...x,order:i}));}
  function normalize(v,now=new Date().toISOString()){if(!v||typeof v!=='object')return null;return{id:clean(v.id,90),version:Math.max(1,Math.round(Number(v.version)||1)),name:clean(v.name,100)||'Ritual sem nome',context:clean(v.context,160),actionType:TYPES.includes(v.actionType)?v.actionType:'study',preparation:items(v.preparation),resources:items(v.resources),cues:items(v.cues),distractions:items(v.distractions),closing:items(v.closing),archived:v.archived===true,isDefault:v.isDefault===true,createdAt:v.createdAt||now,updatedAt:v.updatedAt||now};}
  function snapshot(v){const x=normalize(v);return x?JSON.parse(JSON.stringify({ritualId:x.id,version:x.version,name:x.name,context:x.context,actionType:x.actionType,preparation:x.preparation,resources:x.resources,cues:x.cues,distractions:x.distractions,closing:x.closing})):null;}
  function duplicate(v,id,now=new Date().toISOString()){const x=normalize(v,now);return{...x,id,name:`${x.name} · cópia`,version:1,isDefault:false,archived:false,createdAt:now,updatedAt:now};}
  function update(v,patch,now=new Date().toISOString()){const old=normalize(v,now),next=normalize({...old,...patch,id:old.id,version:old.version+1,createdAt:old.createdAt,updatedAt:now},now);return next;}
  function suggest(templates,item){const type=item?.ritualType||({reading:'reading',study:'study',goal:'planning'})[item?.domain]||null;const ritual=(Array.isArray(templates)?templates:[]).map(normalize).find(x=>x&&!x.archived&&x.actionType===type);return ritual?{ritual,reason:`Sugerido porque o tipo da ação é ${type}. Aplicação opcional.`}:null;}
  function defaults(now='2026-01-01T00:00:00.000Z'){const data={study:['Estudo','Abrir material|Definir pergunta central','Livro ou notas','Sentar no local de estudo','Silenciar notificações','Registrar próxima revisão'],programming:['Programação','Abrir projeto|Definir entrega verificável','Editor e documentação','Executar ambiente local','Fechar abas não relacionadas','Registrar commit ou próximo passo'],reading:['Leitura','Separar livro|Definir trecho','Livro e marcador','Sentar no local de leitura','Afastar notificações','Anotar ideia principal'],writing:['Escrita','Abrir rascunho|Definir seção','Notas de referência','Escrever a primeira frase','Fechar fontes não essenciais','Registrar ponto de retomada'],planning:['Planejamento','Abrir revisão|Listar decisões','Agenda e dados da semana','Começar pelo resultado desejado','Fechar entradas paralelas','Confirmar próximas ações']};return Object.entries(data).map(([type,x],n)=>normalize({id:`ritual-default-${type}`,name:x[0],actionType:type,context:`Template inicial editável de ${x[0].toLowerCase()}`,preparation:x[1].split('|'),resources:[x[2]],cues:[x[3]],distractions:[x[4]],closing:[x[5]],isDefault:true,createdAt:now,updatedAt:now},now));}
  return{TYPES,items,normalize,snapshot,duplicate,update,suggest,defaults};
});
